# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: windows-2022
  demands:
  - msbuild
  - visualstudio

steps:
- task: UseDotNet@2
  displayName: 'Use .NET 6 Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true
    performMultiLevelLookup: true
- task: UseDotNet@2
  displayName: 'Use .NET 5 Core sdk'
  inputs:
    packageType: 'sdk'
    version: '5.x'
    includePreviewVersions: true
    performMultiLevelLookup: true
- task: NuGetToolInstaller@1
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'config'
    nugetConfigPath: 'src\.NuGet\nuget.config'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar'
    organization: 'mouadhjaber'
    scannerMode: 'MSBuild'
    projectKey: '400c5d2dbcd19c9ce84071c1eb43dcb441f26656'
    projectName: 'yourdeals'
    extraProperties: sonar.exclusions=**/*.css,**/*.js
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
    logFileVerbosity : 'diagnostic'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests.dll
      !**\*TestAdapter.dll
      !**\obj\**
      !**\bin\**\ref\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: |
      **\NPComplet.YourDeals.Client.Web.csproj
      **\NPComplet.YourDeals.Server.Api.Blazor.csproj
    arguments: '/p:PublishProfile=UAT_Deploy /p:Password=!3bdQt97'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
