//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPComplet.YourDeals.Translations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NPComplet.YourDeals.Translations.Resources.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags to describe what your Offer is about.
        /// </summary>
        public static string Add_tags_to_describe_what_your_Offer_is_about {
            get {
                return ResourceManager.GetString("Add tags to describe what your Offer is about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags to describe what your Request is about.
        /// </summary>
        public static string Add_tags_to_describe_what_your_Request_is_about {
            get {
                return ResourceManager.GetString("Add tags to describe what your Request is about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add milestone.
        /// </summary>
        public static string AddMilestone {
            get {
                return ResourceManager.GetString("AddMilestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any difficulty, just reply to this email—we&apos;re always happy to help out..
        /// </summary>
        public static string AssistantMessage {
            get {
                return ResourceManager.GetString("AssistantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        public static string Change_Your_Password {
            get {
                return ResourceManager.GetString("Change Your Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process cannot be completed due to error.
        /// </summary>
        public static string ChangePasswordError {
            get {
                return ResourceManager.GetString("ChangePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A link has been sent to your inbox for change of password..
        /// </summary>
        public static string ChangePasswordLink {
            get {
                return ResourceManager.GetString("ChangePasswordLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Confirm_password {
            get {
                return ResourceManager.GetString("Confirm password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create deal.
        /// </summary>
        public static string Create_deal {
            get {
                return ResourceManager.GetString("Create deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create proposition.
        /// </summary>
        public static string Create_proposition {
            get {
                return ResourceManager.GetString("Create proposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Current_password {
            get {
                return ResourceManager.GetString("Current password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal details.
        /// </summary>
        public static string Deal_details {
            get {
                return ResourceManager.GetString("Deal details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals history.
        /// </summary>
        public static string Deals_history {
            get {
                return ResourceManager.GetString("Deals history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string Delete_Account {
            get {
                return ResourceManager.GetString("Delete Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes ?.
        /// </summary>
        public static string Discard_changes__ {
            get {
                return ResourceManager.GetString("Discard changes ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        public static string Email_address {
            get {
                return ResourceManager.GetString("Email address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation.
        /// </summary>
        public static string Email_Confirmation {
            get {
                return ResourceManager.GetString("Email Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finance.
        /// </summary>
        public static string Finance {
            get {
                return ResourceManager.GetString("Finance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string First_name {
            get {
                return ResourceManager.GetString("First name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgetPasswordAssistantMessage {
            get {
                return ResourceManager.GetString("ForgetPasswordAssistantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgetPasswordMsgBody {
            get {
                return ResourceManager.GetString("ForgetPasswordMsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgetPasswordPleaseEmailConfirm {
            get {
                return ResourceManager.GetString("ForgetPasswordPleaseEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgetPasswordTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Forgot_Password_ {
            get {
                return ResourceManager.GetString("Forgot Password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgotPasswordAccountWelcome {
            get {
                return ResourceManager.GetString("ForgotPasswordAccountWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgotPasswordAssistantMessage {
            get {
                return ResourceManager.GetString("ForgotPasswordAssistantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgotPasswordMsgBody {
            get {
                return ResourceManager.GetString("ForgotPasswordMsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgotPasswordPleaseEmailConfirm {
            get {
                return ResourceManager.GetString("ForgotPasswordPleaseEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string ForgotPasswordTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to deal.
        /// </summary>
        public static string GoToDeal {
            get {
                return ResourceManager.GetString("GoToDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login or register.
        /// </summary>
        public static string login_or_register {
            get {
                return ResourceManager.GetString("login or register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for....
        /// </summary>
        public static string Looking_for___ {
            get {
                return ResourceManager.GetString("Looking for...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a proposition.
        /// </summary>
        public static string Make_a_proposition {
            get {
                return ResourceManager.GetString("Make a proposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone.
        /// </summary>
        public static string Milestone_payment {
            get {
                return ResourceManager.GetString("Milestone payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My statistics.
        /// </summary>
        public static string My_statistics {
            get {
                return ResourceManager.GetString("My statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My wallet.
        /// </summary>
        public static string My_wallet {
            get {
                return ResourceManager.GetString("My wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Messages..
        /// </summary>
        public static string No_Messages_ {
            get {
                return ResourceManager.GetString("No Messages.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User selected to Chat With..
        /// </summary>
        public static string No_User_selected_to_Chat_With_ {
            get {
                return ResourceManager.GetString("No User selected to Chat With.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not accepted.
        /// </summary>
        public static string NotAccepted {
            get {
                return ResourceManager.GetString("NotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offers.
        /// </summary>
        public static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string Password_is_required {
            get {
                return ResourceManager.GetString("Password is required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} and at max {1} characters long..
        /// </summary>
        public static string PasswordLengthError {
            get {
                return ResourceManager.GetString("PasswordLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string PasswordSouldConfirm {
            get {
                return ResourceManager.GetString("PasswordSouldConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        public static string Pay_After {
            get {
                return ResourceManager.GetString("Pay After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        public static string Pay_Before {
            get {
                return ResourceManager.GetString("Pay Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Payment_After {
            get {
                return ResourceManager.GetString("Payment After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Payment_Before {
            get {
                return ResourceManager.GetString("Payment Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Kind.
        /// </summary>
        public static string Payment_Kind {
            get {
                return ResourceManager.GetString("Payment Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Manor.
        /// </summary>
        public static string PaymentManor {
            get {
                return ResourceManager.GetString("PaymentManor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment manors.
        /// </summary>
        public static string PaymentManors {
            get {
                return ResourceManager.GetString("PaymentManors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposition.
        /// </summary>
        public static string Proposition {
            get {
                return ResourceManager.GetString("Proposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposition accepeted successfully.
        /// </summary>
        public static string PropositionAcceptanceMessage {
            get {
                return ResourceManager.GetString("PropositionAcceptanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want really accept the proposition with :.
        /// </summary>
        public static string PropositionAcceptanceMessagePopin {
            get {
                return ResourceManager.GetString("PropositionAcceptanceMessagePopin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposition amount.
        /// </summary>
        public static string PropositionAmount {
            get {
                return ResourceManager.GetString("PropositionAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposition created successfully.
        /// </summary>
        public static string PropositionCreationMessage {
            get {
                return ResourceManager.GetString("PropositionCreationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propositions.
        /// </summary>
        public static string Propositions {
            get {
                return ResourceManager.GetString("Propositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and accept .
        /// </summary>
        public static string ReadTermAndWarranty {
            get {
                return ResourceManager.GetString("ReadTermAndWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string RegisterAccountAssistantMessage {
            get {
                return ResourceManager.GetString("RegisterAccountAssistantMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string RegisterAccountMsgBody {
            get {
                return ResourceManager.GetString("RegisterAccountMsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string RegisterAccountPleaseEmailConfirm {
            get {
                return ResourceManager.GetString("RegisterAccountPleaseEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string RegisterAccountTitle {
            get {
                return ResourceManager.GetString("RegisterAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string RegisterAccountWelcome {
            get {
                return ResourceManager.GetString("RegisterAccountWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me ?.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Required_field {
            get {
                return ResourceManager.GetString("Required field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend Verification.
        /// </summary>
        public static string Resend_Verification {
            get {
                return ResourceManager.GetString("Resend Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reset your password by clicking here:.
        /// </summary>
        public static string ResetPasswordMsgBody {
            get {
                return ResourceManager.GetString("ResetPasswordMsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by city, neighborhood or ZIP code.
        /// </summary>
        public static string Search_by_city__neighborhood_or_ZIP_code {
            get {
                return ResourceManager.GetString("Search by city, neighborhood or ZIP code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected propositions.
        /// </summary>
        public static string SelectedPropositions {
            get {
                return ResourceManager.GetString("SelectedPropositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out .
        /// </summary>
        public static string Sign_out {
            get {
                return ResourceManager.GetString("Sign out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        public static string Sorry__there_s_nothing_at_this_address_ {
            get {
                return ResourceManager.GetString("Sorry, there\'s nothing at this address.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the term and the warranty.
        /// </summary>
        public static string TermAndWarranty {
            get {
                return ResourceManager.GetString("TermAndWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term condition.
        /// </summary>
        public static string TermCondition {
            get {
                return ResourceManager.GetString("TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token.
        /// </summary>
        public static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction kind.
        /// </summary>
        public static string Transaction_kind {
            get {
                return ResourceManager.GetString("Transaction kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string VerificationAccountMessage {
            get {
                return ResourceManager.GetString("VerificationAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string VerificationAccountMsgBody {
            get {
                return ResourceManager.GetString("VerificationAccountMsgBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string VerificationAccountPleaseEmailConfirm {
            get {
                return ResourceManager.GetString("VerificationAccountPleaseEmailConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account verification needed.
        /// </summary>
        public static string VerificationAccountTitle {
            get {
                return ResourceManager.GetString("VerificationAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account verification.
        /// </summary>
        public static string VerificationAccountWelcome {
            get {
                return ResourceManager.GetString("VerificationAccountWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranty.
        /// </summary>
        public static string Warranty {
            get {
                return ResourceManager.GetString("Warranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string WelcomeForgetPassword {
            get {
                return ResourceManager.GetString("WelcomeForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Cannot Offer your Self.
        /// </summary>
        public static string You_Cannot_Offer_your_Self {
            get {
                return ResourceManager.GetString("You Cannot Offer your Self", resourceCulture);
            }
        }
    }
}
